# Generated by Django 5.1 on 2024-12-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('services', '0005_alter_services_slug_alter_subservices_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_location_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='employees', to='services.services'),
        ),
    ]
