# Generated by Django 5.1 on 2025-01-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_address_employee_days_available_and_more'),
        ('services', '0005_alter_services_slug_alter_subservices_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='days_available',
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='services.services'),
        ),
        migrations.AddField(
            model_name='employee',
            name='days_available',
            field=models.ManyToManyField(blank=True, to='employee.day'),
        ),
    ]
