# Generated by Django 5.1 on 2025-01-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_day_remove_employee_days_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='location_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
