# Generated by Django 5.1 on 2025-02-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_location_lat_employee_location_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_location_lat',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_location_long',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
