# Generated by Django 5.1 on 2025-02-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='days_available',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
