# Generated by Django 5.1 on 2025-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_employee_days_available_delete_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=10, null=True),
        ),
    ]
