# Generated by Django 5.1 on 2025-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_email_alter_employee_phone_number_and_more'),
        ('services', '0009_remove_subservice_sub_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(upload_to='employee_profiles/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='employees', to='services.service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_hours_start',
            field=models.TimeField(),
        ),
    ]
