# Generated by Django 5.1 on 2024-10-04 06:41

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_service_name', models.CharField(max_length=255)),
                ('sub_service_description', tinymce.models.HTMLField()),
                ('sub_service_image', models.ImageField(upload_to='subservice_images/')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='services.services')),
            ],
        ),
    ]
