# Generated by Django 5.1 on 2024-10-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_service_description_subservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservices',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
