# Generated by Django 5.1 on 2024-10-15 15:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subservices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service_name', unique=True),
        ),
        migrations.AddField(
            model_name='subservices',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='sub_service_name', unique=True),
        ),
    ]
