# Generated by Django 5.0.7 on 2024-10-15 16:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_slug_subservices_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='service_name', unique=True),
        ),
        migrations.AlterField(
            model_name='subservices',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='sub_service_name', unique=True),
        ),
    ]
