# Generated by Django 5.1 on 2025-01-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_service'),
        ('employee', '0005_employee_location_lat_employee_location_long'),
        ('services', '0005_alter_services_slug_alter_subservices_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='SubServices',
            new_name='SubService',
        ),
    ]
