# Generated by Django 5.1 on 2025-02-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_services_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_img',
        ),
    ]
