# Generated by Django 5.1 on 2025-02-14 14:36

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='sub_service_name', unique=True),
        ),
    ]
