# Generated by Django 5.1 on 2025-02-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_subservice_price_alter_subservice_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='sub_service_description',
        ),
    ]
