# Generated by Django 5.1 on 2024-10-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_address_booking_created_at_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
