# Generated by Django 5.1 on 2024-12-17 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_feedback'),
        ('services', '0005_alter_services_slug_alter_subservices_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
    ]
