# Generated by Django 5.1 on 2025-02-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='employee',
            new_name='assigned_employee',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
