# Generated by Django 5.1 on 2025-02-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rate the service from 1 to 5 stars', null=True),
        ),
    ]
