# Generated by Django 5.1 on 2025-02-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
