# Generated by Django 5.1 on 2025-02-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_booking_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(choices=[('0.5', '30 Minutes'), ('1', '1 Hour'), ('2', '2 Hours'), ('3', '3 Hours')], default='0.5', max_length=3),
        ),
    ]
