# Generated by Django 5.1 on 2025-02-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_address_profile_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
